// src/pages/About/About.jsx
import React, { useEffect } from "react";
import Resume from "../../assets/KelechiAmos.pdf";
import ProfileImg from "../../assets/kelechi_amos.jpg";

import "./about.css";
import Aos from "aos";
import "aos/dist/aos.css";

const About = () => {
  useEffect(() => {
    Aos.init({ duration: 1200 });
  }, []);
  return (
    <div id="about" className="about_container">
      <div className="header_text">
        <h1>About</h1>
      </div>
      <div className="about">
        <div className="resume">
          <div id="container_main">
            <div id="wrapper_hero" className="section-page">
              <img id="profile_pic" src={ProfileImg} alt="profile-pics" />

              <div>
                <h2 id="username">Kelechi Amos</h2>
                <p id="bio">Software Engineer</p>
                <a href="mailto:eng.kelechiamos@gmail.com" id="email">
                  eng.kelechiamos@gmail.com
                </a>
              </div>
            </div>

            <section className="section_page">
              <div id="socials_list">
                <a
                  href="https://github.com/kellyncodes"
                  rel="noreferrer"
                  target="_blank"
                >
                  Github
                </a>
                <a href={Resume} download="" rel="noreferrer" target="_blank">
                  Download Resume
                </a>
                <a
                  href="https://www.linkedin.com/in/kellyncodes/"
                  rel="noreferrer"
                  target="_blank"
                >
                  Linkedin
                </a>
                <a
                  href="https://twitter.com/kellyncodes"
                  rel="noreferrer"
                  target="_blank"
                >
                  Twitter
                </a>
                <a
                  href="https://facebook.com/kellyncodes"
                  rel="noreferrer"
                  target="_blank"
                >
                  Facebook
                </a>
              </div>
            </section>

            <section className="section_page skills">
              <div>
                <h2>Programming Languages </h2>
                <ul className="qualification_list">
                  <li>C#</li>
                  <li>JavaScript</li>
                  <li>PHP</li>
                </ul>
              </div>

              <div>
                <h2>S D Ms </h2>
                <ul className="qualification_list">
                  <li>Agile</li>
                  <li>Scrum</li>
                </ul>
              </div>

              <div className="soft_skill">
                <h2>Soft Skills </h2>
                <div className="skill">
                  <ul>
                    <li>Detail-oriented</li>
                    <li>Communicative</li>
                    <li>Leadership</li>
                    <li>Problem-Solving</li>
                    <li>Quality Assurance</li>
                    <li>Instrumentalist</li>
                  </ul>
                </div>
              </div>
            </section>

            <section className="section_page">
              <h2 className="tech_stack">Tech Stack</h2>

              <div id="wrapper_techstack_items">
                <div className="card_techstack">
                  <span>
                    JavaScript | Angular | NextJs | Version control System |
                    Html | Css | Tailwind | Bootstrap.
                  </span>
                </div>

                <div className="card_techstack">
                  <span>C#/.NET | NESTJS | PHP </span>
                </div>

                <div className="card_techstack">
                  <span>SSMS, MYSQL, MONGO DB</span>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};

export default About;

// src/app/pages/about/about.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'kelly-about',
  standalone: true,
  imports: [],
  templateUrl: './about.component.html',
  styleUrl: './about.component.scss'
})
export class AboutComponent {

}

<div id="about" class="about_container" data-aos="zoom-out">
  <div class="header_text">
    <h1>About</h1>
  </div>
  <div class="about">
    <div class="resume">
      <div id="container_main">
        <div id="wrapper_hero" class="section-page">
          <img
            id="profile_pic"
            src="../../../assets/images/kellyncodes.jpg"
            alt="profile-pics"
          />

          <div>
            <h2 id="username">Kelechi Amos</h2>
            <p id="bio">Software Engineer</p>
            <a href="mailto:kelechi.amos.omeh@gmail.com" id="email">
              kelechi.amos.omeh&commat;gmail.com
            </a>
          </div>
        </div>
        <div class="profile">
          <p>
            • Results-driven full-stack software engineer with a proven track
            record in planning and developing highly scalable and secured
            software solutions. Specializing in leveraging C#/.NET and Angular
            to create robust applications that meet the highest standards of
            performance and security.
            <br />
            • Proficient in deploying applications on leading cloud platforms
            such as AWS, Azure, Railway, and Render, ensuring optimal
            functionality and accessibility.
          </p>
        </div>

        <section class="section_page">
          <div id="socials_list">
            <a
              href="https://github.com/kellyncodes"
              rel="noreferrer"
              target="_blank"
            >
              Github
            </a>
            <a
              href="assets/files/Kelechi_Amos_Omeh.pdf"
              download=""
              rel="noreferrer"
              target="_blank"
            >
              Download Resume
            </a>
            <a
              href="https://www.linkedin.com/in/kellyncodes/"
              rel="noreferrer"
              target="_blank"
            >
              Linkedin
            </a>
            <a
              href="https://twitter.com/kellyncodes"
              rel="noreferrer"
              target="_blank"
            >
              Twitter
            </a>
            <a
              href="https://facebook.com/kellyncodes"
              rel="noreferrer"
              target="_blank"
            >
              Facebook
            </a>
          </div>
        </section>

        <section class="section_page skills">
          <div>
            <h2>Programming Languages</h2>
            <ul class="qualification_list">
              <li>C#</li>
              <li>JavaScript</li>
            </ul>
          </div>

          <div>
            <h2>S D Ms</h2>
            <ul class="qualification_list">
              <li>Agile</li>
              <li>Scrum</li>
            </ul>
          </div>

          <div class="soft_skill">
            <h2>Soft Skills</h2>
            <div class="skill">
              <ul>
                <li>Detail-oriented</li>
                <li>Communicative</li>
                <li>Leadership</li>
                <li>Problem-Solving</li>
                <li>Quality Assurance</li>
                <li>Instrumentalist</li>
              </ul>
            </div>
          </div>
        </section>

        <section class="section_page" id="TechStack">
          <h2 class="tech_stack">Tech Stack</h2>

          <div id="wrapper_techstack_items">
            <div class="card_techstack">
              <span>
                JavaScript | Angular | NextJs | Version control System | Html |
                Css | Tailwind | Bootstrap.
              </span>
            </div>

            <div class="card_techstack">
              <span>C#/.NET | NESTJS </span>
            </div>

            <div class="card_techstack">
              <span>SSMS, MYSQL, MONGO DB</span>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>
