// src/components/Footer/Footer.jsx
import { React, useRef } from "react";
import "./footer.css";
import {
  FaTwitter,
  FaLinkedin,
  FaGithub,
  FaDiscord,
  FaRegArrowAltCircleUp,
} from "react-icons/fa";

function Footer() {
  const windowWidth = useRef(window.innerWidth).current;
  return (
    <>
      <div className="footer_container">
        <div className="footer">
          <div className="socials">
            <div className="get_in_touch">
              <h4>Get in touch</h4>
            </div>
            <ul>
              <a
                href="https://github.com/KellynCodes"
                rel="noreferrer"
                target="_blank"
              >
                <FaGithub />
              </a>
              <a
                href="https://www.linkedin.com/in/KellynCodes"
                target="_blank"
                rel="noreferrer"
              >
                <FaLinkedin />
              </a>
              <a
                href="https://twitter.com/kellyncodes"
                rel="noreferrer"
                target="_blank"
              >
                <FaTwitter />
              </a>

              <a
                href="https://discord.com/users/kellyncodes#8004"
                rel="noreferrer"
                target="_blank"
              >
                <FaDiscord />
              </a>
            </ul>
          </div>
        </div>

        <a
          href="#nav"
          className={windowWidth > 700 ? "open_scroll_up" : "close_scroll_up"}
        >
          <FaRegArrowAltCircleUp style={{ fontSize: "1.5rem" }} />
        </a>
      </div>

      <div className="copyright">
        <p>
          CopyRight &copy;
          <b className="footer_year"> {new Date().getFullYear()} </b> All right
          Reserved, Made by <b className="footer_year">KellynCodes</b>
        </p>
      </div>
    </>
  );
}

export default Footer;

// src/app/component/footer/footer.component.ts
import { isPlatformBrowser } from '@angular/common';
import {
  Component,
  PLATFORM_ID,
  Inject,
  signal,
  HostListener,
} from '@angular/core';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import {
  faBrandXTwitter,
  faBrandGithub,
  faBrandLinkedin,
  faBrandDiscord,
  faBrandUpwork,
} from '@ng-icons/font-awesome/brands';
import { faSolidCircleArrowUp } from '@ng-icons/font-awesome/solid';

@Component({
  selector: 'kelly-footer',
  standalone: true,
  imports: [NgIconComponent],
  viewProviders: [
    provideIcons({
      faBrandXTwitter,
      faBrandGithub,
      faBrandLinkedin,
      faBrandDiscord,
      faBrandUpwork,
      faSolidCircleArrowUp,
    }),
  ],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss',
})
export class FooterComponent {
  public year = new Date().getFullYear();
  public isBrowser: boolean;
  public windowScroll = signal<boolean>(false);

  constructor(@Inject(PLATFORM_ID) private platformId: any) {
    this.isBrowser = isPlatformBrowser(this.platformId);
  }

  ngOnInit(): void {
    this.windowScrollCheck();
  }

  @HostListener('window:scroll', ['$event'])
  windowScrollCheck(): void {
    if (this.isBrowser) {
      const isWindowScroll =
        window.innerWidth > 700 && window.innerHeight > 200;
      this.windowScroll.set(isWindowScroll);
    }
  }

  @HostListener('window:resize', ['$event'])
  onWindowResize(event: Event): void {
    if (this.isBrowser) {
      const isWindowScroll =
        window.innerWidth > 700 && window.innerHeight > 200;
      this.windowScroll.set(isWindowScroll);
    }
  }
}

<div class="footer_container">
  <div class="footer">
    <div class="socials">
      <div class="get_in_touch">
        <h4>Get in touch</h4>
      </div>
      <ul>
        <a
          href="https://github.com/KellynCodes"
          rel="noreferrer"
          target="_blank"
        >
          <ng-icon color="#2f5061" name="faBrandGithub" />
        </a>
        <a
          href="https://www.linkedin.com/in/KellynCodes"
          target="_blank"
          rel="noreferrer"
        >
          <ng-icon color="#2f5061" name="faBrandLinkedin" />
        </a>
        <a
          href="https://twitter.com/kellyncodes"
          rel="noreferrer"
          target="_blank"
        >
          <ng-icon color="#2f5061" name="faBrandXTwitter" />
        </a>

        <a
          href="https://discord.com/users/kellyncodes#8004"
          rel="noreferrer"
          target="_blank"
        >
          <ng-icon color="#2f5061" name="faBrandUpwork" />
        </a>
      </ul>
    </div>
  </div>

  <a
    href="#nav"
    [class]="windowScroll() ? 'open_scroll_up' : 'close_scroll_up'"
  >
    <i class="fas fa-arrow-circle-up"></i>
    <ng-icon color="#2f5061" name="faSolidCircleArrowUp" />
  </a>
</div>

<div class="copyright">
  <p>
    CopyRight &copy;
    <b class="footer_year"> {{ year }} </b> All right Reserved, Made by
    <b class="footer_year">KellynCodes</b>
  </p>
</div>
