// src/pages/Home/Home.jsx
import React, { useEffect } from "react";
import { FaDesktop, FaHammer, FaPen } from "react-icons/fa";
import "./home.css";
import Aos from "aos";
import headerImg from "../../assets/form.svg";
import "aos/dist/aos.css";

function Home() {
  useEffect(() => {
    Aos.init({ duration: 1200 });
  }, []);
  return (
    <div id="home" className="home">
      <div data-aos="flip-right" className="home_left">
        <div className="about">
          <div className="me">
            <h3>Hey! I am</h3>
            <h1>Kelly</h1>
          </div>
          <div className="software_engineer">
            <h1>Software Engineer</h1>
          </div>
          <div className="capacity">
            <h5>
              I help your business succeed! by creating trusted softwares to
              manage your business
            </h5>
            <i>Full stack Engineer =&gt;</i>
            <a href="#TechStack"> Tech Stacks</a>
          </div>

          <div className="my_work">
            <ul>
              <h3>The kind of works I do</h3>
              <div className="icon_container">
                <div className="icons">
                  <FaPen />
                </div>
                <p>Project Planning</p>
              </div>
              <div className="icon_container">
                <div className="icons">
                  <FaDesktop />
                </div>
                <p>Software Development</p>
              </div>

              <div className="icon_container">
                <div className="icons">
                  <FaHammer />
                </div>
                <p>Software Maintenance</p>
              </div>
            </ul>
          </div>
        </div>
      </div>

      <div data-aos="flip-right" className="home_right">
        <img src={headerImg} alt="profile_image" />
      </div>
    </div>
  );
}

export default Home;

// src/app/pages/home/home.component.ts
import { Component } from '@angular/core';
import { ProjectsComponent } from '../projects/projects.component';
import { ContactComponent } from '../contact/contact.component';
import { AboutComponent } from '../about/about.component';
import { LoaderComponent } from '../../component/loader/loader.component';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { faSolidLaptopCode, faSolidPen } from '@ng-icons/font-awesome/solid';

@Component({
  selector: 'kelly-home',
  standalone: true,
  imports: [
    AboutComponent,
    ProjectsComponent,
    ContactComponent,
    LoaderComponent,
    NgIconComponent,
  ],
  viewProviders: [
    provideIcons({
      faSolidLaptopCode,
      faSolidPen,
    }),
  ],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
})
export class HomeComponent {}

<div id="home" class="home">
  <div class="home_left" data-aos="flip-left" data-aos-delay="500">
    <div class="about">
      <div class="me">
        <h3>Hey! I am</h3>
        <h1>Kelly</h1>
      </div>
      <div class="software_engineer">
        <h1>Software Engineer</h1>
      </div>
      <div class="capacity">
        <h5>
          I help your business succeed! by creating trusted softwares to manage
          your business
        </h5>
        <i>Full stack Engineer =&gt;</i>
        <a href="#TechStack"> Tech Stacks</a>
      </div>

      <div class="my_work">
        <ul>
          <h3>The kind of works I do</h3>
          <div class="icon_container">
            <div class="icons">
              <ng-icon name="faSolidPen" />
            </div>
            <p>Project Planning</p>
          </div>
          <div class="icon_container">
            <div class="icons">
              <ng-icon name="faSolidLaptopCode" />
            </div>
            <p>Software Development</p>
          </div>

          <div class="icon_container">
            <div class="icons">
              <ng-icon name="faSolidLaptopCode" />
            </div>
            <p>Software Maintenance</p>
          </div>
        </ul>
      </div>
    </div>
  </div>

  <div class="home_right" data-aos="flip-right" data-aos-delay="600">
    <img src="assets/svg/form.svg" alt="profile_image" />
  </div>
</div>

<kelly-about />

@defer {
<kelly-projects />
}@loading(minimum 500ms) {
<blog-loader loadingText="Loading Project Gallery..." />
}@error {
<p class="text-red-500 font-bold bg-white z-50">Failed to load projects</p>
}

<kelly-contact />
